= metanorma-ribose: Asciidoctor processor for Ribose Standard Documents 

image:https://img.shields.io/gem/v/metanorma-rsd.svg["Gem Version", link="https://rubygems.org/gems/metanorma-rsd"]
image:https://github.com/metanorma/metanorma-rsd/workflows/macos/badge.svg["Build Status (macOS)", link="https://github.com/metanorma/metanorma-rsd/actions?workflow=macos"]
image:https://github.com/metanorma/metanorma-rsd/workflows/ubuntu/badge.svg["Build Status (ubuntu)", link="https://github.com/metanorma/metanorma-rsd/actions?workflow=ubuntu"]
image:https://github.com/metanorma/metanorma-rsd/workflows/windows/badge.svg["Build Status (Windows)", link="https://github.com/metanorma/metanorma-rsd/actions?workflow=windows"]
image:https://codeclimate.com/github/metanorma/metanorma-rsd/badges/gpa.svg["Code Climate", link="https://codeclimate.com/github/metanorma/metanorma-rsd"]
image:https://img.shields.io/github/issues-pr-raw/metanorma/metanorma-rsd.svg["Pull Requests", link="https://github.com/metanorma/metanorma-rsd/pulls"]
image:https://img.shields.io/github/commits-since/metanorma/metanorma-rsd/latest.svg["Commits since latest",link="https://github.com/metanorma/metanorma-rsd/releases"]

_Formerly known as_ `asciidoctor-rsd`, `metanorma-rsd`.

== Functionality

This gem processes http://asciidoctor.org/[Asciidoctor] documents following
the Metanorma model for generating Ribose standards.

The gem currently inherits from the https://github.com/metanorma/metanorma-standoc
gem, and aligns closely to it. Refer to https://metanorma.com[] for guidance.

== Usage

The preferred way to invoke this gem is via the `metanorma` script:

[source,console]
----
$ metanorma --type ribose a.adoc                   # output HTML and DOC
$ metanorma --type ribose --extensions html a.adoc # output just HTML
$ metanorma --type ribose --extensions doc a.adoc  # output just DOC
$ metanorma --type ribose --extensions xml a.adoc  # output Metanorma XML
----

The gem translates the document into Metanorma XML format, and then
validates its output against the Ribopse Metanorma XML document model; errors are
reported to console against the XML, and are intended for users to
check that they have provided all necessary components of the
document.

The gem then converts the XML into output formats such as HTML and PDF.

=== Installation

If you are using a Mac, the https://github.com/metanorma/metanorma-macos-setup
repository has instructions on setting up your machine to run Metanorma
scripts such as this one. You need only run the following in a Terminal console:

[source,console]
----
$ bash <(curl -s https://raw.githubusercontent.com/metanorma/metanorma-macos-setup/master/metanorma-setup)
$ gem install metanorma-rsd
$ gem install metanorma-cli
----

== Documentation

See https://www.metanorma.com/author/ribose/[The Ribose flavor of Metanorma]


== Data Models

The Ribose Standard Document format is an instance of the
https://github.com/metanorma/metanorma-model-standoc[StandardDocument model]. Details of
this general model can be found on its page. Details of the Ribose modifications
to this general model can be found on the https://github.com/metanorma/metanorma-model-rsd[RSD model]
repository.

== Examples

Example documents may be found in the https://github.com/metanorma/mn-samples-ribose[mn-samples-ribose]
repository.

